/**
 * ANALYTICS IDENTITY — pure. No network, no clock, no Supabase.
 * ---------------------------------------------------------------------------
 * The one place identity facts become classification facts. The full
 * canonical classifier (classify / inPopulation, consumed by both the
 * live rollup and snapshots) lands in the next phase ON TOP of what is
 * here; this module owns the identity-derivation half it will stand on.
 *
 * ── THE APPROVED ASYMMETRY, AS CODE ──────────────────────────────────
 *
 * A device that has ever carried an approved INTERNAL account may have
 * its ANONYMOUS events classified internal. That is the whole rule.
 *
 *   ⛔ It derives 'internal' ONLY. Never 'public', never 'beta' — a
 *      device seen with an ordinary account says nothing about its
 *      other users, and deriving public would delete real people.
 *   ⛔ It is CLASSIFICATION, never ATTRIBUTION. No anonymous event is
 *      ever claimed to have been generated by a specific person.
 *   · Attributed rows never consult it: user_id present → that
 *     account's segment, full stop. Internal wins only among the
 *     ANONYMOUS rows of a mixed device.
 */

export const SEGMENTS = Object.freeze({
  INTERNAL: 'internal',
  BETA: 'beta',
  TEST: 'test',
  PUBLIC: 'public', // the default; stored as ABSENCE, never as a row
});

/** Segments a stored row may carry — 'public' is deliberately not one. */
export const STORABLE_SEGMENTS = Object.freeze([SEGMENTS.INTERNAL, SEGMENTS.BETA, SEGMENTS.TEST]);

/**
 * Populations a report can ask for. `all` is genuinely unfiltered —
 * the D6 lesson: a view that promises everything must deliver it.
 */
export const POPULATIONS = Object.freeze(['public', 'internal', 'beta', 'test', 'all']);

/**
 * ⭐⭐ THE CANONICAL CLASSIFIER. The only one. The live summary and the
 * historical snapshot rebuild both import THIS function; a second
 * implementation anywhere is audit defect D4 reborn, and a guard test
 * greps for one.
 *
 * Resolution order, exactly as ratified:
 *   1. user_id present → that account's segment (or public by absence).
 *      An attributed row NEVER consults the device map — the account is
 *      the person and always wins.
 *   2. user_id absent → the derived device segment, which by
 *      construction (deriveDeviceSegments) can only ever be 'internal'.
 *   3. otherwise public. Unknown never silently becomes internal.
 *
 * @param row      {user_id, device_id}
 * @param segments {users: {user_id: segment}, devices: {device_id: 'internal'}}
 */
export function classify(row, segments) {
  const s = segments || {};
  if (row?.user_id) return (s.users || {})[row.user_id] ?? SEGMENTS.PUBLIC;
  const byDevice = row?.device_id ? (s.devices || {})[row.device_id] : null;
  return byDevice === SEGMENTS.INTERNAL ? SEGMENTS.INTERNAL : SEGMENTS.PUBLIC;
}

/** Does this population include this row? */
export function inPopulation(row, segments, population) {
  if (population === 'all') return true;
  return classify(row, segments) === population;
}

/**
 * The derived device→segment map.
 *
 * @param links        [{device_id, user_id}] — analytics.identity_links
 * @param userSegments {user_id: segment}    — analytics.account_segments
 * @returns            {device_id: 'internal'} — internal entries ONLY
 */
export function deriveDeviceSegments(links, userSegments) {
  const out = {};
  for (const l of links || []) {
    if ((userSegments || {})[l.user_id] === SEGMENTS.INTERNAL) {
      out[l.device_id] = SEGMENTS.INTERNAL;
    }
  }
  return out;
}

/**
 * Which witnessed (device, account) pairs have no link yet — the
 * sweep's arithmetic, pure so idempotency is a property, not a hope.
 * Feeding the same pairs twice yields [] the second time by
 * construction, because the first run's inserts appear in `links`.
 *
 * @param witnessed [{device_id, user_id, first_seen}] distinct pairs from raw events
 * @param links     [{device_id, user_id}] existing identity links
 */
export function missingLinks(witnessed, links) {
  const have = new Set((links || []).map((l) => l.device_id + '|' + l.user_id));
  return (witnessed || []).filter((w) => w.user_id && !have.has(w.device_id + '|' + w.user_id));
}

/**
 * What a member-add does to classification — decided here, not in the
 * route, so the precedence is testable.
 *
 *   · team has no default_segment            → nothing (public by absence)
 *   · account already classified             → nothing; an existing row —
 *     'direct' above all — is a deliberate fact a roster edit must not
 *     overwrite. ⛔ Never downgrade, never upgrade, never touch.
 *   · otherwise                              → materialise the default as an
 *     explicit row, source 'team_default', so the database explains itself.
 *
 * @returns null, or the segment row to insert
 */
export function segmentRowForNewMember({ team, userId, existingSegment }) {
  if (!team?.default_segment) return null;
  if (existingSegment) return null;
  if (!STORABLE_SEGMENTS.includes(team.default_segment)) return null;
  return {
    user_id: userId,
    segment: team.default_segment,
    source: 'team_default',
    note: 'default of team: ' + (team.name ?? team.id),
  };
}
