-- ============================================================
-- AV3 · IDENTITY LINKS — the auditable device↔account relationship
--
-- ⚠ NOT YET APPLIED. Run after AV2.
--
-- A link records that a device has, at some moment, carried an
-- authenticated account. That is ALL it records.
--
-- ⛔⛔ A LINK IS NEVER PERSON ATTRIBUTION. It never claims an anonymous
-- row was generated by the linked person, and nothing may ever read it
-- that way. Its two legitimate uses, both defined in the approved
-- Analytics v2 decisions:
--
--   1. INTERNAL-DEVICE CLASSIFICATION (asymmetric, internal-only): a
--      device that has ever carried an approved internal account may
--      have its ANONYMOUS rows classified internal. Never applied to
--      derive 'public' or 'beta'. Classification, not authorship.
--   2. RESOLVED ATTRIBUTION in funnels, always labelled 'resolved',
--      never blended with raw attribution (arrives Phase D).
--
-- Append-only: no UPDATE path exists or will. method records
-- provenance —
--   'backfill'  derived once, below, from the historical raw events
--   'observed'  written by the service's idempotent sweep as new
--               attributed rows arrive
--
-- ⛔ RAW EVENTS ARE NOT TOUCHED. The backfill READS public.usage_events
-- and writes only this table. usage_events.user_id is never rewritten,
-- here or anywhere, ever.
-- ============================================================

CREATE TABLE IF NOT EXISTS analytics.identity_links (
  id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  device_id  uuid NOT NULL,
  user_id    uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  linked_at  timestamptz NOT NULL DEFAULT now(),
  method     text NOT NULL CHECK (method IN ('observed', 'backfill')),
  UNIQUE (device_id, user_id)
);

CREATE INDEX IF NOT EXISTS identity_links_user_idx
  ON analytics.identity_links (user_id);

ALTER TABLE analytics.identity_links ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON analytics.identity_links FROM PUBLIC, anon, authenticated;
GRANT  ALL ON analytics.identity_links TO service_role;

-- ── THE ONE-TIME HISTORICAL BACKFILL ────────────────────────────
--
-- Every (device, account) pair the raw record has ever witnessed.
-- linked_at is the FIRST co-occurrence — the moment the relationship
-- became a fact — not now(): a link stamped with its run date would
-- claim every historical relationship began today.
-- Idempotent: re-running cannot duplicate (unique) or overwrite
-- (DO NOTHING preserves an earlier linked_at and any 'observed' row).
INSERT INTO analytics.identity_links (device_id, user_id, linked_at, method)
SELECT device_id, user_id, min(created_at), 'backfill'
  FROM public.usage_events
 WHERE user_id IS NOT NULL
 GROUP BY device_id, user_id
ON CONFLICT (device_id, user_id) DO NOTHING;

-- ============================================================
-- VERIFICATION
-- ============================================================

-- V1 · table exists, closed, append-only in privilege terms.
DO $$
BEGIN
  IF to_regclass('analytics.identity_links') IS NULL THEN
    RAISE EXCEPTION 'V1 FAILED: analytics.identity_links does not exist';
  END IF;
  IF has_table_privilege('anon', 'analytics.identity_links', 'SELECT')
     OR has_table_privilege('authenticated', 'analytics.identity_links', 'SELECT') THEN
    RAISE EXCEPTION 'V1 FAILED: identity links readable with a public key';
  END IF;
  RAISE NOTICE 'V1 PASSED: identity_links exists, service_role-only';
END $$;

-- V2 · the backfill agrees with the raw record it was derived from.
-- Positive both ways: every witnessed pair has a link, and no link
-- exists that the raw record cannot justify.
DO $$
DECLARE missing int; unjustified int; pairs int;
BEGIN
  SELECT count(*) INTO missing FROM (
    SELECT DISTINCT device_id, user_id FROM public.usage_events WHERE user_id IS NOT NULL
  ) raw
  WHERE NOT EXISTS (
    SELECT 1 FROM analytics.identity_links l
    WHERE l.device_id = raw.device_id AND l.user_id = raw.user_id
  );
  IF missing <> 0 THEN
    RAISE EXCEPTION 'V2 FAILED: % witnessed (device,account) pair(s) have no link', missing;
  END IF;

  SELECT count(*) INTO unjustified FROM analytics.identity_links l
  WHERE l.method = 'backfill'
    AND NOT EXISTS (
      SELECT 1 FROM public.usage_events e
      WHERE e.device_id = l.device_id AND e.user_id = l.user_id
    );
  IF unjustified <> 0 THEN
    RAISE EXCEPTION 'V2 FAILED: % backfill link(s) have no supporting raw event', unjustified;
  END IF;

  SELECT count(*) INTO pairs FROM analytics.identity_links;
  RAISE NOTICE 'V2 PASSED: % link(s), each justified by the raw record', pairs;
END $$;

-- V3 · raw events untouched: same row count and attribution split as
-- before this migration could possibly have altered (it holds no
-- UPDATE/DELETE on usage_events, but the assertion is cheap and the
-- claim matters).
DO $$
DECLARE total bigint; attributed bigint;
BEGIN
  SELECT count(*), count(user_id) INTO total, attributed FROM public.usage_events;
  RAISE NOTICE 'V3 PASSED: usage_events intact — % rows, % attributed (record these against the audit: 41,444+ / 28,606+ as at 2026-08-28)', total, attributed;
END $$;
